version: '3.8'
services:
  user-service:
    build: ./user-service
    ports:
      - "8081:8081"
    depends_on:
      - postgres
  product-service:
    build: ./product-service
    ports:
      - "8082:8082"
    depends_on:
      - postgres
  order-service:
    build: ./order-service
    ports:
      - "8083:8083"
    depends_on:
      - postgres
  payment-service:
    build: ./payment-service
    ports:
      - "8084:8084"
    depends_on:
      - postgres
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
